pipeline{
  agent any
  stages{
    stage(CodeCheckOut'){
      steps {
        script{
        checkout scm
        def mvHome = tool 'maven-3'
        }
       }
     }
    stage('Build'){
      steps {
        sh 'mvn -B clean package'
       }
     }
  }
}
    
     
